//! Retarded imaginary-time interaction kernels for the longitudinal
//! spin-boson cluster solver.
//!
//! The bath representation stores the normalized measure proportional to
//! `J(omega) / (pi omega)`.  If its total mass is `lambda`, then
//!
//! `K_beta(tau) = lambda * E_q[omega * D_beta(omega, tau)]`,
//!
//! with the symmetric thermal propagator
//!
//! `D_beta = (exp(-omega tau) + exp(-omega (beta-tau))) /
//!           (1-exp(-beta omega))`.

use crate::impurity::spin_boson::bath::Bath;
use crate::impurity::spin_boson::cluster::segments::{TimeInterval, WorldlineSegment};
use crate::impurity::ImpurityError;

const DEFAULT_QUADRATURE_ORDER: usize = 64;
const MIN_QUADRATURE_ORDER: usize = 4;
const MAX_QUADRATURE_ORDER: usize = 512;

#[derive(Debug, Clone, Copy, PartialEq)]
struct SpectralPoint {
    omega: f64,
    mass: f64,
}

/// Positive retarded kernel generated by a Gaussian bosonic bath.
#[derive(Debug, Clone, PartialEq)]
pub struct RetardedKernel {
    lambda: f64,
    points: Vec<SpectralPoint>,
}

impl RetardedKernel {
    /// Construct from a normalized bath shape and total spectral mass
    /// `lambda = int d omega J(omega) / (pi omega)`.
    pub fn new(bath: &Bath, lambda: f64, quadrature_order: usize) -> Result<Self, ImpurityError> {
        if !lambda.is_finite() || lambda < 0.0 {
            return Err(ImpurityError::parameter(
                "lambda",
                format!("must be finite and non-negative, got {lambda}"),
            ));
        }
        let points = spectral_points(bath, quadrature_order)?;
        Ok(Self { lambda, points })
    }

    /// Construct with the default power-law quadrature order.
    pub fn with_default_quadrature(bath: &Bath, lambda: f64) -> Result<Self, ImpurityError> {
        Self::new(bath, lambda, DEFAULT_QUADRATURE_ORDER)
    }

    /// Total normalized spectral mass.
    #[inline]
    pub const fn lambda(&self) -> f64 {
        self.lambda
    }

    /// Number of precomputed spectral quadrature points.
    #[inline]
    pub fn quadrature_points(&self) -> usize {
        self.points.len()
    }

    /// Evaluate `K_beta(delta_tau)` for a periodic time difference.
    pub fn value(&self, beta: f64, delta_tau: f64) -> Result<f64, ImpurityError> {
        validate_beta(beta)?;
        let delta = delta_tau.rem_euclid(beta);
        Ok(self.lambda
            * self
                .points
                .iter()
                .map(|point| point.mass * omega_times_thermal_propagator(point.omega, beta, delta))
                .sum::<f64>())
    }

    /// Evaluate `int_I d tau int_J d tau' K_beta(tau-tau')` for two
    /// different circular segments.
    pub fn integrated_segments(
        &self,
        beta: f64,
        left: &WorldlineSegment,
        right: &WorldlineSegment,
    ) -> Result<f64, ImpurityError> {
        validate_beta(beta)?;
        let mut total = 0.0;
        for &left_piece in left.pieces() {
            for &right_piece in right.pieces() {
                total += self.integrated_intervals(beta, left_piece, right_piece)?;
            }
        }
        Ok(total)
    }

    /// Evaluate the integrated kernel between two non-overlapping intervals.
    pub fn integrated_intervals(
        &self,
        beta: f64,
        left: TimeInterval,
        right: TimeInterval,
    ) -> Result<f64, ImpurityError> {
        validate_beta(beta)?;
        let (first, second) = order_disjoint_intervals(left, right)?;
        Ok(self.lambda
            * self
                .points
                .iter()
                .map(|point| point.mass * integrated_frequency(point.omega, beta, first, second))
                .sum::<f64>())
    }
}

/// Parameters of the longitudinal spin-boson Hamiltonian
///
/// `H = -(Delta/2) sigma_x + (epsilon/2) sigma_z
///      + sigma_z sum_k g_k (b_k + b_k^dagger)
///      + sum_k omega_k b_k^dagger b_k`.
///
/// In this module the bath spectral density is defined from the coefficients
/// that multiply `sigma_z` directly, `J_sigma(omega)=pi sum_k g_k^2
/// delta(omega-omega_k)`. A single mode therefore has total kernel mass
/// `lambda = g_k^2/omega_k`.
#[derive(Debug, Clone, PartialEq)]
pub struct LongitudinalSpinBosonModel {
    bath: Bath,
    kernel: RetardedKernel,
    tunnelling: f64,
    bias: f64,
}

impl LongitudinalSpinBosonModel {
    /// Construct a longitudinal model.
    pub fn new(
        bath: Bath,
        lambda: f64,
        tunnelling: f64,
        bias: f64,
        quadrature_order: usize,
    ) -> Result<Self, ImpurityError> {
        if !tunnelling.is_finite() || tunnelling < 0.0 {
            return Err(ImpurityError::parameter(
                "tunnelling",
                format!("must be finite and non-negative, got {tunnelling}"),
            ));
        }
        if !bias.is_finite() {
            return Err(ImpurityError::parameter(
                "epsilon",
                format!("must be finite, got {bias}"),
            ));
        }
        let kernel = RetardedKernel::new(&bath, lambda, quadrature_order)?;
        Ok(Self {
            bath,
            kernel,
            tunnelling,
            bias,
        })
    }

    /// Construct with the default power-law quadrature order.
    pub fn with_default_quadrature(
        bath: Bath,
        lambda: f64,
        tunnelling: f64,
        bias: f64,
    ) -> Result<Self, ImpurityError> {
        Self::new(bath, lambda, tunnelling, bias, DEFAULT_QUADRATURE_ORDER)
    }

    /// Bath shape.
    #[inline]
    pub const fn bath(&self) -> &Bath {
        &self.bath
    }

    /// Integrated retarded kernel.
    #[inline]
    pub const fn kernel(&self) -> &RetardedKernel {
        &self.kernel
    }

    /// Tunnel splitting `Delta`.
    #[inline]
    pub const fn tunnelling(&self) -> f64 {
        self.tunnelling
    }

    /// Poisson cut rate `Gamma = Delta/2`.
    #[inline]
    pub fn transverse_rate(&self) -> f64 {
        0.5 * self.tunnelling
    }

    /// Longitudinal bias `epsilon` in `(epsilon/2) sigma_z`.
    #[inline]
    pub const fn bias(&self) -> f64 {
        self.bias
    }

    /// Total spectral mass `int J(omega)/(pi omega) d omega`.
    #[inline]
    pub const fn lambda(&self) -> f64 {
        self.kernel.lambda()
    }
}

fn spectral_points(
    bath: &Bath,
    quadrature_order: usize,
) -> Result<Vec<SpectralPoint>, ImpurityError> {
    match bath {
        Bath::SingleMode(mode) => Ok(vec![SpectralPoint {
            omega: mode.omega(),
            mass: 1.0,
        }]),
        Bath::Tabulated(table) => {
            let mut previous = 0.0;
            let points = table
                .frequencies()
                .iter()
                .zip(table.cumulative())
                .map(|(&omega, &cumulative)| {
                    let mass = cumulative - previous;
                    previous = cumulative;
                    SpectralPoint { omega, mass }
                })
                .filter(|point| point.mass > 0.0)
                .collect::<Vec<_>>();
            if points.is_empty() {
                return Err(ImpurityError::InvalidBathTable(
                    "tabulated bath has no positive spectral mass".into(),
                ));
            }
            Ok(points)
        }
        Bath::PowerLaw(power) => {
            let order = quadrature_order.clamp(MIN_QUADRATURE_ORDER, MAX_QUADRATURE_ORDER);
            let quadrature = gauss_legendre_unit(order);
            Ok(quadrature
                .into_iter()
                .map(|(u, mass)| SpectralPoint {
                    // The transformation omega=omega_c*u^(1/s) turns the
                    // normalized J/omega measure exactly into du.
                    omega: power.cutoff() * u.powf(1.0 / power.exponent()),
                    mass,
                })
                .collect())
        }
    }
}

fn validate_beta(beta: f64) -> Result<(), ImpurityError> {
    if !beta.is_finite() || beta <= 0.0 {
        Err(ImpurityError::parameter(
            "beta",
            format!("must be finite and positive, got {beta}"),
        ))
    } else {
        Ok(())
    }
}

fn omega_times_thermal_propagator(omega: f64, beta: f64, delta: f64) -> f64 {
    if beta * omega <= 1e-8 {
        return 2.0 / beta;
    }
    let denominator = -(-beta * omega).exp_m1();
    omega * ((-omega * delta).exp() + (-omega * (beta - delta)).exp()) / denominator
}

fn order_disjoint_intervals(
    left: TimeInterval,
    right: TimeInterval,
) -> Result<(TimeInterval, TimeInterval), ImpurityError> {
    if left.end() <= right.start() {
        Ok((left, right))
    } else if right.end() <= left.start() {
        Ok((right, left))
    } else {
        Err(ImpurityError::InvalidConfiguration(format!(
            "retarded bond intervals overlap: [{}, {}) and [{}, {})",
            left.start(),
            left.end(),
            right.start(),
            right.end()
        )))
    }
}

fn integrated_frequency(omega: f64, beta: f64, first: TimeInterval, second: TimeInterval) -> f64 {
    if beta * omega <= 1e-8 {
        return 2.0 * first.length() * second.length() / beta;
    }
    let first_factor = -(-omega * first.length()).exp_m1();
    let second_factor = -(-omega * second.length()).exp_m1();
    let denominator = -(-beta * omega).exp_m1();
    let direct_gap = (second.start() - first.end()).max(0.0);
    let wrap_gap = (beta - second.end() + first.start()).max(0.0);
    first_factor * second_factor * ((-omega * direct_gap).exp() + (-omega * wrap_gap).exp())
        / (omega * denominator)
}

/// Generate Gauss-Legendre nodes and weights on `[0,1]`.
fn gauss_legendre_unit(order: usize) -> Vec<(f64, f64)> {
    let mut result = vec![(0.0, 0.0); order];
    let half = order.div_ceil(2);
    let order_f = order as f64;
    for index in 0..half {
        let index_f = index as f64;
        let mut root = (std::f64::consts::PI * (index_f + 0.75) / (order_f + 0.5)).cos();
        for _ in 0..32 {
            let (value, derivative) = legendre_with_derivative(order, root);
            let updated = root - value / derivative;
            if (updated - root).abs() <= 8.0 * f64::EPSILON * updated.abs().max(1.0) {
                root = updated;
                break;
            }
            root = updated;
        }
        let (_, derivative) = legendre_with_derivative(order, root);
        let weight = 2.0 / ((1.0 - root * root) * derivative * derivative);
        let left = 0.5 * (1.0 - root);
        let right = 0.5 * (1.0 + root);
        let unit_weight = 0.5 * weight;
        result[index] = (left, unit_weight);
        result[order - 1 - index] = (right, unit_weight);
    }
    result
}

fn legendre_with_derivative(order: usize, x: f64) -> (f64, f64) {
    let mut p_previous = 1.0;
    let mut p_current = x;
    if order == 0 {
        return (1.0, 0.0);
    }
    if order == 1 {
        return (x, 1.0);
    }
    for degree in 2..=order {
        let degree_f = degree as f64;
        let p_next =
            ((2.0 * degree_f - 1.0) * x * p_current - (degree_f - 1.0) * p_previous) / degree_f;
        p_previous = p_current;
        p_current = p_next;
    }
    let derivative = order as f64 * (x * p_current - p_previous) / (x * x - 1.0);
    (p_current, derivative)
}

#[cfg(test)]
mod tests {
    use crate::impurity::spin_boson::bath::{PowerLawBath, SingleModeBath, TabulatedBath};

    use super::*;

    #[test]
    fn quadrature_weights_are_normalized() {
        for order in [4, 8, 16, 64] {
            let total = gauss_legendre_unit(order)
                .iter()
                .map(|(_, weight)| weight)
                .sum::<f64>();
            assert!((total - 1.0).abs() < 1e-13);
        }
    }

    #[test]
    fn single_mode_kernel_has_kms_symmetry() {
        let bath = Bath::SingleMode(SingleModeBath::new(1.7).expect("mode"));
        let kernel = RetardedKernel::with_default_quadrature(&bath, 0.4).expect("kernel");
        let beta = 5.0;
        let left = kernel.value(beta, 1.3).expect("value");
        let right = kernel.value(beta, beta - 1.3).expect("value");
        assert!((left - right).abs() < 1e-14);
    }

    #[test]
    fn integrated_single_mode_kernel_matches_midpoint_reference() {
        let bath = Bath::SingleMode(SingleModeBath::new(1.2).expect("mode"));
        let kernel = RetardedKernel::with_default_quadrature(&bath, 0.7).expect("kernel");
        let beta = 4.0;
        let left = TimeInterval::new(0.2, 0.9, beta).expect("interval");
        let right = TimeInterval::new(1.4, 2.5, beta).expect("interval");
        let exact = kernel
            .integrated_intervals(beta, left, right)
            .expect("integral");
        let bins = 800usize;
        let mut reference = 0.0;
        for i in 0..bins {
            let tau = left.start() + (i as f64 + 0.5) * left.length() / bins as f64;
            for j in 0..bins {
                let tau_prime = right.start() + (j as f64 + 0.5) * right.length() / bins as f64;
                reference += kernel.value(beta, tau_prime - tau).expect("value");
            }
        }
        reference *= left.length() * right.length() / (bins * bins) as f64;
        assert!((exact - reference).abs() < 2e-7);
    }

    #[test]
    fn tabulated_masses_recover_cumulative_differences() {
        let bath =
            Bath::Tabulated(TabulatedBath::new(vec![1.0, 2.0], vec![1.0, 3.0]).expect("table"));
        let kernel = RetardedKernel::new(&bath, 2.0, 8).expect("kernel");
        assert_eq!(kernel.quadrature_points(), 2);
    }

    #[test]
    fn power_law_quadrature_converges_for_kernel_value() {
        let bath = Bath::PowerLaw(PowerLawBath::new(0.6, 2.0).expect("bath"));
        let coarse = RetardedKernel::new(&bath, 0.3, 32).expect("kernel");
        let fine = RetardedKernel::new(&bath, 0.3, 128).expect("kernel");
        let coarse_value = coarse.value(6.0, 1.1).expect("value");
        let fine_value = fine.value(6.0, 1.1).expect("value");
        assert!((coarse_value - fine_value).abs() < 2e-7);
    }
}
